title = "gitleaks config for .env file"

[extend]
path = "central-gitleaks.toml"

[[rules]]
description = "MongoDB Root Username in .env"
regex = '''(?i)(^MONGO_INITDB_ROOT_USERNAME=).+'''
tags = ["mongodb", "username"]

[[rules]]
description = "MongoDB Root Password in .env"
regex = '''(?i)(^MONGO_INITDB_ROOT_PASSWORD=).+'''
tags = ["mongodb", "password"]

[[rules]]
description = "MongoDB URI in .env"
regex = '''(?i)(^MONGODB_URI=).+'''
tags = ["mongodb", "uri"]

[[rules]]
description = "DB Username in .env"
regex = '''(?i)(^DB_USERNAME=").+'''
tags = ["username"]

[[rules]]
description = "DB Password in .env"
regex = '''(?i)(^DB_PASSWORD=").+'''
tags = ["password"]

[[rules]]
description = "Generic Secret in .env"
regex = '''(?i)(^.+=).+secret.+'''
tags = ["secret"]
